name: sip_phone_call
description: A Flutter package for sip phone voip call
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2

  sip_ua:
    git:
      url: https://github.com/anhlevfx/dart-sip-ua.git
      ref: master

  callkeep:
    git:
      url: https://github.com/ltnghia97/callkeep.git
      path: callkeep-master
      ref: main
#
  flutter_vibration:
      git:
        url: https://github.com/ltnghia97/flutter_vibration.git
        path: flutter-vibration-master
        ref: main

  intl: ^0.18.0
  equatable: ^2.0.3
  lottie: ^2.3.2
  socket_io_client: ^2.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  package_info: ^2.0.0
  proximity_sensor: ^1.0.4
  fluttertoast: ^8.2.1
  firebase_core: ^3.1.0
  audio_session: ^0.1.16
  firebase_messaging: ^15.0.1

  flutter_local_notifications: ^15.1.1
  uuid: ^3.0.6
  flutter_broadcasts:
    git:
      url: https://github.com/anhlevfx/flutter_broadcasts.git
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/graphics/
    - assets/json/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
